services:
  Aligent\ABNBundle\Form\Extension\RegistrationTypeExtension:
    calls:
      - [setConfigManager, ['@oro_config.manager']]
      - [setSubscriber, ['@Aligent\ABNBundle\Form\EventListener\FrontendCustomerUserRegistrationTypeSubscriber']]
    tags:
      - { name: form.type_extension, extended_type: Oro\Bundle\CustomerBundle\Form\Type\FrontendCustomerUserRegistrationType }

  Aligent\ABNBundle\Form\EventListener\FrontendCustomerUserRegistrationTypeSubscriber:
    arguments:
      - '@doctrine'
      - '@oro_config.manager'

  Aligent\ABNBundle\Form\Type\CustomerGroupSelectType:
    arguments:
      - '@doctrine'
    tags:
        - { name: form.type, alias: aligent_abn_customer_group_select }